# Generated by Django 5.1.3 on 2025-05-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_university_universitycourses_college_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='Place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='University_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='universitycourses',
            name='University_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='universitycourses',
            name='course_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
