# Generated by Django 5.1.3 on 2025-06-25 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_university_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourses',
            name='University_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.university'),
        ),
        migrations.AlterField(
            model_name='universitycourses',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.courses'),
        ),
    ]
