# Generated by Django 5.1.3 on 2025-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_universitycourses_university_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycourses',
            name='University_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='universitycourses',
            name='course_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
