# Generated by Django 5.2.1 on 2025-06-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_universitycourses_university_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycourses',
            old_name='course_id',
            new_name='courseid',
        ),
    ]
