# Generated by Django 5.2.1 on 2025-07-01 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_course_id_universitycourses_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='University_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.university'),
        ),
    ]
