# Generated by Django 5.2.1 on 2025-07-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_college_university_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='College/'),
        ),
    ]
